### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by WAY29** [maxtacu/kali-linux-docker#4]
OS：centos7
when I build this images,i got a error on step 12: 

ERROR: Could not find a version that satisfies the requirement urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.20.0->-r /usr/lib/web/requirements.txt (line 14)) (from versions: none)
ERROR: No matching distribution found for urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.20.0->-r /usr/lib/web/requirements.txt (line 14))

could you tell me what happen?

**Comment by maxtacu** [comment]
Let me check the build on CentOS and will come back with an update

**Comment by maxtacu** [comment]
Build is successful on latest Centos 7 and docker.
I used this vagrantfile - https://app.vagrantup.com/lpf/boxes/centos7docker
and installed additionally git to clone the project.

**Comment by maxtacu** [comment]
Additionally updated repo with pip upgrade, but it works with the previous version as well

**Comment by WAY29** [comment]
> Additionally updated repo with pip upgrade, but it works with the previous version as well

when I try to build after you update, I got a other error:/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "exec: \"/startup.sh\": permission denied".
I solved it by RUN chmod 777 /startup.sh and successfully build it. but when I go to http://127.0.0.1:6080/, I found 502 Bad Gateway.I am sad.

**Comment by WAY29** [comment]
> Additionally updated repo with pip upgrade, but it works with the previous version as well

I try to build it on Ubuntu 18.04 and all seems fine.But when I go to http://127.0.0.1:6080/, I found 500 Internal Server.service is not ready, please restart container.Restart doesn't work.

**Comment by maxtacu** [comment]
@WAY29 yeah, I got the error as well. Thanks for the update. Today will be the fix and will update the thread as well

**Comment by maxtacu** [comment]
Issue is fixed. Please pull the latest changes. Sorry for taking it so long, was busy with work stuff. Stay safe!
