### ISSUE TITLE
Docker image won't build with `python-pip`

### ISSUE THREAD

**Issue by uxdom** [maxtacu/kali-linux-docker#6]
Hey @maxtacu nice job with this project!

I am building the docker image but receiving 

`E: Package 'python-pip' has no installation candidate`

Looks like its something to do with `apt install python-pip` package. 
Python Packaging Authority started to remove the python2 from repositories, I believe.

When changing `python-pip` to `python3-pip` in `Dockerfile` I am progressing the build till the end but unfortunately the following error occurs:

` Downloading wsgiref-0.1.2.zip (37 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8bqibueq/wsgiref_1528c82a54e9481e9e17aa01f935348c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8bqibueq/wsgiref_1528c82a54e9481e9e17aa01f935348c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-s1qbri8a
         cwd: /tmp/pip-install-8bqibueq/wsgiref_1528c82a54e9481e9e17aa01f935348c/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8bqibueq/wsgiref_1528c82a54e9481e9e17aa01f935348c/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-install-8bqibueq/wsgiref_1528c82a54e9481e9e17aa01f935348c/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install setuptools wheel && pip install -r /usr/lib/web/requirements.txt' returned a non-zero code: 1 `

**Comment by maxtacu** [comment]
Hey @uxdom I think you're right with python removal. As far as I know they are removing only `python` packages, but `python2` and `python3` are still there. You can try to build the image with `python2`.
Meanwhile I will check the project build process. Maybe something else as well was deprecated and needs to be updated.
Thanks for the feedback

**Comment by maxtacu** [comment]
so after building the project on my machine I found the problem. Seems like official `kalilinux/kali-rolling` image was updated with python3 as default already present python version
I will migrate the whole project to python3
